import type { User, Category, Expense } from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "Alex",
  email: "alex@example.com",
  baseCurrency: "USD",
};

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Food & Dining",
    icon: "UtensilsCrossed",
    color: "#E67E22",
    userId: "user-1",
  },
  {
    id: "cat-2",
    name: "Transport",
    icon: "Car",
    color: "#3498DB",
    userId: "user-1",
  },
  {
    id: "cat-3",
    name: "Groceries",
    icon: "ShoppingCart",
    color: "#3D8A5A",
    userId: "user-1",
  },
  {
    id: "cat-4",
    name: "Entertainment",
    icon: "Film",
    color: "#9B59B6",
    userId: "user-1",
  },
  {
    id: "cat-5",
    name: "Health",
    icon: "Heart",
    color: "#E74C3C",
    userId: "user-1",
  },
  {
    id: "cat-6",
    name: "Housing",
    icon: "Home",
    color: "#2ECC71",
    userId: "user-1",
  },
  {
    id: "cat-7",
    name: "Shopping",
    icon: "ShoppingBag",
    color: "#1ABC9C",
    userId: "user-1",
  },
  {
    id: "cat-8",
    name: "Utilities",
    icon: "Zap",
    color: "#F39C12",
    userId: "user-1",
  },
];

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const mockExpenses: Expense[] = [
  {
    id: "exp-1",
    amount: 12.5,
    currency: "USD",
    baseAmount: 12.5,
    baseCurrency: "USD",
    description: "Coffee & bagel",
    date: daysAgo(0),
    categoryId: "cat-1",
    category: mockCategories[0],
    userId: "user-1",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "exp-2",
    amount: 45.0,
    currency: "USD",
    baseAmount: 45.0,
    baseCurrency: "USD",
    description: "Uber ride",
    date: daysAgo(0),
    categoryId: "cat-2",
    category: mockCategories[1],
    userId: "user-1",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "exp-3",
    amount: 89.99,
    currency: "USD",
    baseAmount: 89.99,
    baseCurrency: "USD",
    description: "Weekly groceries",
    date: daysAgo(0),
    categoryId: "cat-3",
    category: mockCategories[2],
    userId: "user-1",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "exp-4",
    amount: 15.99,
    currency: "USD",
    baseAmount: 15.99,
    baseCurrency: "USD",
    description: "Netflix subscription",
    date: daysAgo(1),
    categoryId: "cat-4",
    category: mockCategories[3],
    userId: "user-1",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "exp-5",
    amount: 32.0,
    currency: "USD",
    baseAmount: 32.0,
    baseCurrency: "USD",
    description: "Lunch with team",
    date: daysAgo(1),
    categoryId: "cat-1",
    category: mockCategories[0],
    userId: "user-1",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "exp-6",
    amount: 25.0,
    currency: "USD",
    baseAmount: 25.0,
    baseCurrency: "USD",
    description: "Pharmacy",
    date: daysAgo(2),
    categoryId: "cat-5",
    category: mockCategories[4],
    userId: "user-1",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "exp-7",
    amount: 1200.0,
    currency: "USD",
    baseAmount: 1200.0,
    baseCurrency: "USD",
    description: "Rent payment",
    date: daysAgo(3),
    categoryId: "cat-6",
    category: mockCategories[5],
    userId: "user-1",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "exp-8",
    amount: 67.5,
    currency: "USD",
    baseAmount: 67.5,
    baseCurrency: "USD",
    description: "New headphones",
    date: daysAgo(3),
    categoryId: "cat-7",
    category: mockCategories[6],
    userId: "user-1",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "exp-9",
    amount: 85.0,
    currency: "USD",
    baseAmount: 85.0,
    baseCurrency: "USD",
    description: "Electric bill",
    date: daysAgo(4),
    categoryId: "cat-8",
    category: mockCategories[7],
    userId: "user-1",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "exp-10",
    amount: 22.0,
    currency: "USD",
    baseAmount: 22.0,
    baseCurrency: "USD",
    description: "Gas station",
    date: daysAgo(4),
    categoryId: "cat-2",
    category: mockCategories[1],
    userId: "user-1",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "exp-11",
    amount: 55.0,
    currency: "USD",
    baseAmount: 55.0,
    baseCurrency: "USD",
    description: "Dinner at Italian place",
    date: daysAgo(5),
    categoryId: "cat-1",
    category: mockCategories[0],
    userId: "user-1",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "exp-12",
    amount: 120.0,
    currency: "USD",
    baseAmount: 120.0,
    baseCurrency: "USD",
    description: "Groceries (Costco)",
    date: daysAgo(5),
    categoryId: "cat-3",
    category: mockCategories[2],
    userId: "user-1",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "exp-13",
    amount: 40.0,
    currency: "EUR",
    baseAmount: 43.2,
    baseCurrency: "USD",
    description: "Museum tickets",
    date: daysAgo(6),
    categoryId: "cat-4",
    category: mockCategories[3],
    userId: "user-1",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "exp-14",
    amount: 18.0,
    currency: "USD",
    baseAmount: 18.0,
    baseCurrency: "USD",
    description: "Yoga class",
    date: daysAgo(6),
    categoryId: "cat-5",
    category: mockCategories[4],
    userId: "user-1",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "exp-15",
    amount: 95.0,
    currency: "USD",
    baseAmount: 95.0,
    baseCurrency: "USD",
    description: "New running shoes",
    date: daysAgo(7),
    categoryId: "cat-7",
    category: mockCategories[6],
    userId: "user-1",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
];
